project_id = "nadafculrumyvrxsflnf"

[functions.analyze-discovery]
verify_jwt = false

[functions.recommend-templates]
verify_jwt = false

[functions.test-agent]
verify_jwt = false

[functions.create-in-darwin]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.fetch-hubspot-deals]
verify_jwt = false
